### ISSUE TITLE
请求接口发现返回 415 错误

### ISSUE THREAD

**Issue by 666sxrA** [wibus-wee/koishi-plugin-deep-danbooru#6]
### Describe the bug

第一次安装，不管怎么使用，都无响应，日志如下

### Reproduction

AxiosError: Request failed with status code 413

### System Info

```Shell
AxiosError: Request failed with status code 413
                            at settle (C:\koishi-desktop-win-x64-v0.7.3\data\instances\default\node_modules\axios\dist\node\axios.cjs:1268:12)
                            at IncomingMessage.handleStreamEnd (C:\koishi-desktop-win-x64-v0.7.3\data\instances\default\node_modules\axios\dist\node\axios.cjs:2446:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
哈哈 我也没有发现这个问题，最近没有怎么用这个了

刚刚去翻了一下 hugging face 这个 space 发现接口改动了, 转用了 websocket，这导致这个插件无法正常使用了... 解决方案我正在寻找 很抱歉

**Comment by 666sxrA** [comment]
大佬给力  辛苦了QWQ

**Comment by wibus-wee** [comment]
我目前改了一个新的 API，应该是可用了，不过能用的 API 越来越少了...

**Comment by wibus-wee** [comment]
bug fixed in release `v1.1.0`

**Comment by 666sxrA** [comment]
[38;5;8m2022-11-15 23:37:39[0m [D] [38;5;32;1mgocqhttp[0m 收到好友 lᵒᵛᵉᵧₒᵤ(31*********) 的消息: 鉴赏 [CQ:image,file=b63fef9d5c769e028d6521e7d2bb3d3b.image,url=https://c2cpicdw.qpic.cn/offpic_new/0/31*******85-221440081-B63FEF9D5C769E028D6521E7D2BB3D3B/0?term=3] (1006934331)
[38;5;8m2022-11-15 23:37:39[0m [D] [38;5;32;1mgocqhttp[0m 发送好友 311*******585(31*********85)  的消息: [{"type":" ... (453137020)
[38;5;8m2022-11-15 23:37:42[0m [W] [38;5;215;1mcommand[0m deepdanbooru <image file="b63fef9d5c769e028d6521e7d2bb3d3b.image" url="https://c2cpicdw.qpic.cn/offpic_new/0/3115347585-221440081-B63FEF9D5C769E028D6521E7D2BB3D3B/0?term=3"/>
                        AxiosError: Request failed with status code 413
                            at settle (C:\koishi-desktop-win-x64-v0.7.3\data\instances\default\node_modules\axios\dist\node\axios.cjs:1268:12)
                            at IncomingMessage.handleStreamEnd (C:\koishi-desktop-win-x64-v0.7.3\data\instances\default\node_modules\axios\dist\node\axios.cjs:2446:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)

好像问题依然存在

**Comment by wibus-wee** [comment]
奇怪 413？你运行bot的机器能访问hugging face吗？

**Comment by 666sxrA** [comment]
是可以的

**Comment by 666sxrA** [comment]
https://huggingface.co/spaces/hysts/DeepDanbooru
这个页面在服务器上是可以正常使用的

**Comment by wibus-wee** [comment]
那我明天再看看吧，还以为修好了（尴尬尴尬）抱歉抱歉

当奇怪的是我本地可以的啊，你确定装的最新版本而且API用的默认值吗？

你试试重装一下，第一个保证版本是 1.1.0 的，之后插件设置点一下恢复默认值看看

**Comment by wibus-wee** [comment]
不过你是全部图片都这样吗？

**Comment by 666sxrA** [comment]
是不是koishi的原因，大佬要是可以的话，帮我上服务器瞧瞧？

**Comment by 666sxrA** [comment]
我全部的图片都是这个报错

**Comment by 666sxrA** [comment]
都是返回一个正在鉴赏

**Comment by wibus-wee** [comment]
emmmmmmmmmmmm...那我明天具体再看看吧 刚刚关电脑了哈哈哈😂

**Comment by wibus-wee** [comment]
你发一张你的图片过来看看

**Comment by 666sxrA** [comment]
![Cache_337e91fa654ae0af](https://user-images.githubusercontent.com/83914942/201965026-0d95092f-dc5c-43b0-b9ca-d7064a0d3b2e.jpg)

**Comment by wibus-wee** [comment]
omg. 很抱歉😭 昨天是我发包发错了😭 传了一个旧的版本上去 你现在再试试

**Comment by 666sxrA** [comment]
可以了
